gitea:
  admin:
    username: admin
    password: admin12345
# postgresql:
#   enabled: true
#   postgresqlPassword: admin

global:
  storageClass: openebs-hostpath

persistence:
  enabled: true
  storageClass: "openebs-hostpath"

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: gitea.hbarve1.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

